version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/trading.db:/app/backend/trading.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://backend:8000
      - VITE_WS_URL=ws://backend:8000/ws/live
    depends_on:
      - backend
    restart: unless-stopped
